main: com.killianmonnier.sectumsempra.Main
name: Sectumsempra
version: 1.0
api-version: 1.15
description: Juste un petit plugin Harry potter
author: Killian Monnier https://www.linkedin.com/in/killian-monnier/
website: www.killianmonnier.com

commands:
  sectumsempra:
    aliases: ss
  wand: